--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/thebigcrafter/XPShop
build-by-default: true
branches:
- main
projects:
  XPShop:
    path: ""
    libs:
    - src: dktapps-pm-pl/pmforms/pmforms
      version: ^2.1.0
    - src: thebigcrafter/Hydrogen/Hydrogen
      version: ^1.0.0
    - src: mintodev/libMCUnicodeChars/libMCUnicodeChars
      version: ^1.1.0
    - src: DaPigGuy/libPiggyEconomy/libPiggyEconomy
      version: ^3.0.2
...
