--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TobyDev265/XPShop
build-by-default: true
branches:
- main
projects:
  XPShop:
    path: ""
    icon: icon.png
    libs:
    - src: Vecnavium/FormsUI/FormsUI
      version: ^1.1.2
    - src: ifera-mc/UpdateNotifier/UpdateNotifier
      version: ^2.1.0
    - src: mintodev/libMCUnicodeChars/libMCUnicodeChars
      version: ^1.1.0
...
