name: XPShops
authors: [tobydev27, thebigcrafter]
version: 2.1.0
description: Buy and sell XP
api: [5.0.0]
main: tobydev27\XPShop\Main
softdepend: ["BedrockEconomy", "EconomyAPI"]

commands:
  xpshop:
    description: XP Shop
    permission: xpshop.cmd

permissions:
  xpshop.cmd:
    description: Allow players to use XPShop command
    default: op
