name: XPShops
author: MintoD
version: 1.2.0
description: Buy and sell XP
api: [4.0.0]
main: MintoD\XPShop\Main
depend: [BedrockEconomy]

commands:
  xpshop:
    description: XP Shop
    permission: xpshop.cmd

permissions:
  xpshop.cmd:
    description: Allow players to use XPShop command
    default: op
